// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-h2O2hJXc20MD6djrys2upWFYu4WEyWg',
    appId: '1:1019962707674:android:4f46ea9bf0800a7b525fe3',
    messagingSenderId: '1019962707674',
    projectId: 'launchpad-alu-d2aa2',
    storageBucket: 'launchpad-alu-d2aa2.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcR2rTDjgA-u7UV9B979-PvJ5RIqtZso',
    appId: '1:1019962707674:web:3e5fe25a129b262a525fe3',
    messagingSenderId: '1019962707674',
    projectId: 'launchpad-alu-d2aa2',
    authDomain: 'launchpad-alu-d2aa2.firebaseapp.com',
    storageBucket: 'launchpad-alu-d2aa2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcR2rTDjgA-u7UV9B979-PvJ5RIqtZso',
    appId: '1:1019962707674:web:8ca89049a6ba3236525fe3',
    messagingSenderId: '1019962707674',
    projectId: 'launchpad-alu-d2aa2',
    authDomain: 'launchpad-alu-d2aa2.firebaseapp.com',
    storageBucket: 'launchpad-alu-d2aa2.firebasestorage.app',
  );
}
